### ISSUE TITLE
X's Z Saber wave is disabled during intro stage fight with Mac.

### ISSUE THREAD

**Issue by delta7890** [justin3009/MMX3-ZeroProject#13]
When playing on "New Game Plus" and choosing to start the game as Zero, X's Z Saber fails to produce a wave attack in Mac's mini-boss room.  This issue occurs only in this room, and only when fighting as X.  If starting the game as X, Zero's Z Saber wave works just fine in Mac's room.

**Comment by justin3009** [comment]
Fixed.

So what caused this is there's code that specifically checks if there is an NPC Active at the time, if so, it disables the Z-Saber wave from happening... buuuut the problem here is that the "Zero NPC" is active in this scene.

Just added a separate check for the introduction level in the "Disable" code. If it's that stage, just enable the Z-Saber Wave.
