### ISSUE TITLE
Worm Seeker-R (Neon Tiger mid-boss) does not take full damage from Z Saber wave

### ISSUE THREAD

**Issue by delta7890** [justin3009/MMX3-ZeroProject#14]
Have found that the mid-stage boss of Neon Tiger's stage does not take full (if any) damage from a Z Saber wave.  While the wave hits and plays the "swirling" animation as it would on a boss or tough enemy, it does not appear to deal significant damage by itself.  The actual blade of the Z Saber however can dispatch the boss in just a couple hits.

This appears to be a bug specific to TZP, as the saber wave can't hit Worm Seeker-R at all in the base game.

**Comment by justin3009** [comment]
I just noticed this as well and was about to check the damage table on it.

**Comment by justin3009** [comment]
Okay so.. this one might be weird to fix and I can't really ascertain why it's happening.

So it actually DOES damage the boss.. but then when it's doing all of it's other junk that needs to happen behind the scenes, instead of resetting the life back to the proper value, it instead ADDS more life to it after.

It's constantly doing a thing that adds +40 and -40 to the value but specifically for this boss it seems like, it adds the 40 and never actually REMOVES it after. I have no idea why or what sets that but.. yeah.

**Comment by delta7890** [comment]
Weird.  I wonder if there's something funky going on with this boss that prompted the original devs to just say "screw it!" and thus made the boss immune to the wave attack entirely.

**Comment by justin3009** [comment]
It looks like it's a similar issue I had with Mac and Mao The Giant. The damage function doesn't ACTUALLY support the saber wave properly. I'm trying to figure out exactly why though and I'm struggling like crazy.

**Comment by justin3009** [comment]
FIXED IT! GOD that was frustrating but it works now!

**Comment by delta7890** [comment]
Can confirm this is now fixed!  Worm Seeker-R now dies after just three hits from a Z Saber wave!
